--  2022년 3월의  OFFLINE_SALE 테이블의 판매 데이터의 USER_ID 값은 NULL 로 표시해주세요. 판매일을 기준으로 오름차순  상품 ID를 기준으로 오름차순 유저 ID를 기준으로 오름차순 .SELECT SALES_DATE PRODUCT_ID, NVL(USER_ID, 'NULL'), SALES_AMOUNT FROM OFFLINE_SALE OFF WHERE EXTRACT( FROM SALES_DATE) = 2022-03

SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 3

UNION ALL

SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE, PRODUCT_ID,NULL AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE SALES_DATE LIKE "2022-03%"

ORDER BY 1, 2, 3
